import { useState } from 'react';

type SortOption = 'latest' | 'popular' | 'oldest';

const DISPATCHES = [
  {
    id: "dossier-001",
    number: "DOSSIER #001",
    status: "FEATURED DISPATCH",
    title: "Beyond Human Exceptionalism: 5 Mind-Bending Insights Into Orca Culture",
    subtitle: "What if intelligence isn't a ladder climbing toward humanity, but a vast, interconnected evolutionary tree?",
    readTime: "12 min read",
    category: "Marine Cognition & Ecotypes",
    date: "2026-10-01",
    views: 24500,
    summary: "Decades of groundbreaking research in neuroscience and marine biology are dismantling our assumptions about mind and social complexity. Explore how learned cultural traditions in orcas drive biological evolution.",
    excerpt: "In the coastal waters of the Pacific Northwest, distinct orca communities share overlapping ranges yet live in complete cultural isolation—separated by diet, vocal dialects, and multi-generational traditions."
  },
  {
    id: "dossier-002",
    number: "DOSSIER #002",
    status: "IN DEVELOPMENT",
    title: "The Clarion-Clipperton Abyss: Deep Sea Mining vs. The Unknown Biosphere",
    subtitle: "At 4,000 meters depth, electric vehicle battery minerals lie on pristine ecosystems older than humanity.",
    readTime: "9 min read",
    category: "Ecological Finance & Geopolitics",
    date: "2026-10-05",
    views: 8900,
    summary: "As global markets rush to secure nickel and cobalt for green energy transition, international waters become the next geopolitical battleground.",
    excerpt: "Sediment plumes generated by underwater harvesting technology could travel thousands of kilometers through twilight zones, blinding deep-diving species."
  },
  {
    id: "dossier-003",
    number: "DOSSIER #003",
    status: "ARCHIVE DISPATCH",
    title: "Posidonia Oceanica: The Ancient Carbon Guardians of the Mediterranean",
    subtitle: "Clonal seagrass meadows nearly 100,000 years old are silently suffocating under coastal development.",
    readTime: "7 min read",
    category: "Deep Ecology & Restoration",
    date: "2026-09-15",
    views: 31200,
    summary: "A dive into the subterranean root systems that store 10 times more carbon per hectare than tropical rainforests.",
    excerpt: "Trapped in oxygen-poor mats under seabed sands, Posidonia meadows hold ancient environmental records stretching back to the Pleistocene."
  }
];

// CONTINUOUS MIND TIMELINE DATA
const TIMELINE_STAGES = [
  {
    id: "epoch-01",
    tag: "1 BILLION YEARS AGO",
    title: "The Molecular Mind & Universal Currency",
    subtitle: "Single-celled decision making without a central brain",
    description: "Brain-like decision making operates at a molecular level in E. coli bacteria. The exact same electrochemical principles—voltage-gated ion movement across membranes—power both single cells and modern human neurons.",
    highlight: "Information Loop: Acquire (Detect Toxins/Sugars) → Process & Analyze → Act (Swim Toward/Away)",
    statLabel: "Shared Biology",
    statValue: "100% Conserved Ion Channels"
  },
  {
    id: "epoch-02",
    tag: "600-550 MILLION YEARS AGO",
    title: "Nerve Nets & The Cephalization Blueprint",
    subtitle: "From decentralized radial nets to centralized anterior brains",
    description: "In organisms like jellyfish, decentralized nerve nets evolved the 'action potential'—a digital electrical pulse. Later bilaterians centralized these nerves into anterior ganglia, creating the anatomical blueprint for every central nervous system on Earth today.",
    highlight: "Cephalization: Structural reorganization of nerve cords into an anterior brain.",
    statLabel: "Neural Impulse",
    statValue: "Digital Spike Transmission"
  },
  {
    id: "epoch-03",
    tag: "DEEP-TIME PARALLEL PEAKS",
    title: "Cephalization Scaling: Human vs. Orca Neuroanatomy",
    subtitle: "Scaling changes processing capacity, not fundamental biology",
    description: "Decades of neurobiology reveal no qualitatively unique brain property in humans. The Orca brain (~5,000g, EQ 4-5) possesses the most convoluted cortical gyrification on Earth, with massive elaboration in insular and limbic regions.",
    highlight: "Cortical Folding: Orca brains feature higher surface wrinkling and limbic complexity than human brains.",
    statLabel: "Orca Brain Mass",
    statValue: "~5,000 Grams"
  },
  {
    id: "epoch-04",
    tag: "CULTURE AS EVOLUTIONARY FORCE",
    title: "When Behavior Shapes Biology",
    subtitle: "How non-human traditions create genetic divergence",
    description: "When information processing scales, it generates culture. Orcas exhibit extreme dietary conservatism, distinct vocal dialects, and post-reproductive matriarchal leadership that store ancestral knowledge for generations.",
    highlight: "The Grandmother Effect: Post-menopausal matriarchs guide pods through ecological crisis.",
    statLabel: "Cultural Isolation",
    statValue: "700,000+ Years"
  },
  {
    id: "epoch-05",
    tag: "THE BIG FIVE DOMAINS",
    title: "Dismantling Human Exceptionalism",
    subtitle: "Ubiquitous cognitive traits across the tree of life",
    description: "The central question of astrobiology and philosophy has already been answered on Earth: Self-awareness, tool use, culture, numerical logic, and symbolic communication are deeply conserved properties across species.",
    highlight: "We do not sit atop a ladder; we are simply one young leaf on an ancient, intelligent tree.",
    statLabel: "Cognitive Domains",
    statValue: "5 Shared Arenas"
  }
];

export default function App() {
  const [submitted, setSubmitted] = useState(false);
  const [activeArticleId, setActiveArticleId] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<SortOption>('latest');
  const [selectedEcotype, setSelectedEcotype] = useState<'resident' | 'transient'>('resident');
  const [isPlayingAudio, setIsPlayingAudio] = useState(false);
  const [activeStageIndex, setActiveStageIndex] = useState(0);
  const [paradigmMode, setParadigmMode] = useState<'myth' | 'reality'>('reality');

  const selectedArticle = DISPATCHES.find(d => d.id === activeArticleId);
  const currentStage = TIMELINE_STAGES[activeStageIndex];

  const sortedDispatches = [...DISPATCHES].sort((a, b) => {
    if (sortBy === 'latest') {
      return new Date(b.date).getTime() - new Date(a.date).getTime();
    }
    if (sortBy === 'oldest') {
      return new Date(a.date).getTime() - new Date(a.date).getTime();
    }
    if (sortBy === 'popular') {
      return b.views - a.views;
    }
    return 0;
  });

  return (
    <div className="min-h-screen bg-[#030914] text-slate-100 font-sans selection:bg-[#CCFF00] selection:text-black relative overflow-x-hidden">
      
      {/* FULL-BLEED BACKGROUND VIDEO FOR HOME FEED */}
      {!selectedArticle && (
        <div className="absolute top-0 left-0 w-full h-[650px] overflow-hidden pointer-events-none z-0">
          <video 
            autoPlay 
            loop 
            muted 
            playsInline 
            ref={(el) => { if (el) el.muted = true; }}
            className="w-full h-full object-cover opacity-45 scale-105"
          >
            <source src="/bubble.mp4" type="video/mp4" />
          </video>
          <div className="absolute inset-0 bg-gradient-to-b from-[#030914]/40 via-[#030914]/60 to-[#030914]"></div>
        </div>
      )}

      {/* FIXED NAVBAR */}
      <header className="sticky top-0 z-50 bg-[#030914]/80 backdrop-blur-md border-b border-slate-800/80 px-6 py-4">
        <div className="flex items-center justify-between max-w-6xl mx-auto">
          <div 
            className="flex items-center gap-2 cursor-pointer"
            onClick={() => setActiveArticleId(null)}
          >
            <span className="w-2.5 h-2.5 rounded-full bg-[#CCFF00] animate-pulse"></span>
            <span className="font-bold tracking-widest text-sm text-slate-200">DEEP DISPATCHES</span>
          </div>
          
          <div className="flex items-center gap-4">
            {activeArticleId && (
              <button 
                onClick={() => setActiveArticleId(null)}
                className="text-xs text-[#CCFF00] hover:underline font-mono cursor-pointer"
              >
                ← Back to All Dispatches
              </button>
            )}
            <span className="text-xs text-slate-500 uppercase tracking-widest border border-slate-800 rounded-full px-3 py-1 hidden sm:inline-block">
              Independent Media
            </span>
          </div>
        </div>
      </header>

      {/* ARTICLE READER VIEW */}
      {selectedArticle ? (
        <main className="py-16 space-y-16 relative z-10">
          
          {/* ARTICLE HEADER (OPTIMIZED NARROW READING COLUMN) */}
          <div className="max-w-3xl mx-auto px-6 space-y-4">
            <div className="flex items-center gap-3 text-xs font-mono text-[#CCFF00]">
              <span>{selectedArticle.number}</span>
              <span>·</span>
              <span>{selectedArticle.category}</span>
            </div>
            <h1 className="text-3xl md:text-5xl font-extrabold text-white leading-tight">
              {selectedArticle.title}
            </h1>
            <p className="text-lg text-[#CCFF00]/90 font-light italic">
              {selectedArticle.subtitle}
            </p>
            <div className="text-xs text-slate-500 font-mono pt-2 border-b border-slate-800/80 pb-6 flex items-center gap-4">
              <span>Reading Time: {selectedArticle.readTime}</span>
              <span>·</span>
              <span>Status: {selectedArticle.status}</span>
            </div>
          </div>

          {/* INTRO TEXT (NARROW READING COLUMN) */}
          <div className="max-w-3xl mx-auto px-6 prose prose-invert text-slate-300 font-light leading-relaxed space-y-6 text-base md:text-lg">
            <p className="first-letter:text-5xl first-letter:font-bold first-letter:text-[#CCFF00] first-letter:mr-3 first-letter:float-left">
              For centuries, human philosophy and Western science rested on a comfortable dogma: that culture, language, and abstract thought were exclusive domains of <em>Homo sapiens</em>. Animals had instincts; humans had intellect.
            </p>
            <p>
              However, deep beneath the surface waters of the world's oceans, marine biologists and neuroscientists are encountering a reality that shatters our anthropocentric pedestal. Orcas (<em>Orcinus orca</em>) do not merely possess high intelligence—they live inside ancient, non-human cultures shaped by dialect, specialized diets, and multi-generational knowledge systems.
            </p>
          </div>

          {/* SCROLLYTELLING COMPONENT 1: ACOUSTIC MAPPING (WIDE SCREEN BREAKOUT) */}
          <section className="max-w-6xl mx-auto px-4 md:px-6 my-12">
            <div className="bg-[#081225]/80 border border-slate-800 rounded-3xl p-6 md:p-10 space-y-6 shadow-2xl backdrop-blur-md">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800 pb-4">
                <div>
                  <span className="text-[10px] font-mono text-[#CCFF00] tracking-widest uppercase block mb-1">
                    // SCROLLYTELLING MODULE 01
                  </span>
                  <h3 className="text-xl font-bold text-white">
                    Acoustic-Spatial Ecotype Mapping
                  </h3>
                </div>

                {/* ECOTYPE SELECTOR TOGGLE */}
                <div className="flex items-center gap-2 bg-[#030914] p-1.5 rounded-xl border border-slate-800 text-xs font-mono">
                  <button
                    onClick={() => setSelectedEcotype('resident')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                      selectedEcotype === 'resident'
                        ? 'bg-[#CCFF00] text-black font-semibold'
                        : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Resident (Inland)
                  </button>
                  <button
                    onClick={() => setSelectedEcotype('transient')}
                    className={`px-3 py-1.5 rounded-lg transition-all cursor-pointer ${
                      selectedEcotype === 'transient'
                        ? 'bg-[#CCFF00] text-black font-semibold'
                        : 'text-slate-400 hover:text-white'
                    }`}
                  >
                    Transient (Offshore)
                  </button>
                </div>
              </div>

              {/* MAP CONTAINER WITH HOTSPOTS */}
              <div className="relative rounded-2xl overflow-hidden border border-slate-800/80 bg-[#030914] group">
                <img 
                  src="/orca-map.svg" 
                  alt="Pacific Northwest Orca Migration Map" 
                  className="w-full h-auto object-cover min-h-[350px]"
                />