import { useState } from 'react';

type SortOption = 'latest' | 'popular' | 'oldest';

const DISPATCHES = [
  {
    id: "dossier-001",
    number: "DOSSIER #001",
    status: "FEATURED DISPATCH",
    title: "Beyond Human Exceptionalism: 5 Mind-Bending Insights Into Orca Culture",
    subtitle: "What if intelligence isn't a ladder climbing toward humanity, but a vast, interconnected evolutionary tree?",
    readTime: "12 min read",
    category: "Marine Cognition & Ecotypes",
    date: "2026-10-01",
    views: 24500,
    summary: "Decades of groundbreaking research in neuroscience and marine biology are dismantling our assumptions about mind and social complexity. Explore how learned cultural traditions in orcas drive biological evolution.",
    excerpt: "In the coastal waters of the Pacific Northwest, distinct orca communities share overlapping ranges yet live in complete cultural isolation—separated by diet, vocal dialects, and multi-generational traditions.",
    content: "What does it truly mean to be intelligent? For centuries, human philosophy and science have harbored a deep-seated desire to view our species as fundamentally unique..."
  },
  {
    id: "dossier-002",
    number: "DOSSIER #002",
    status: "IN DEVELOPMENT",
    title: "The Clarion-Clipperton Abyss: Deep Sea Mining vs. The Unknown Biosphere",
    subtitle: "At 4,000 meters depth, electric vehicle battery minerals lie on pristine ecosystems older than humanity.",
    readTime: "9 min read",
    category: "Ecological Finance & Geopolitics",
    date: "2026-10-05",
    views: 8900,
    summary: "As global markets rush to secure nickel and cobalt for green energy transition, international waters become the next geopolitical battleground.",
    excerpt: "Sediment plumes generated by underwater harvesting technology could travel thousands of kilometers through twilight zones, blinding deep-diving species.",
    content: ""
  },
  {
    id: "dossier-003",
    number: "DOSSIER #003",
    status: "ARCHIVE DISPATCH",
    title: "Posidonia Oceanica: The Ancient Carbon Guardians of the Mediterranean",
    subtitle: "Clonal seagrass meadows nearly 100,000 years old are silently suffocating under coastal development.",
    readTime: "7 min read",
    category: "Deep Ecology & Restoration",
    date: "2026-09-15",
    views: 31200,
    summary: "A dive into the subterranean root systems that store 10 times more carbon per hectare than tropical rainforests.",
    excerpt: "Trapped in oxygen-poor mats under seabed sands, Posidonia meadows hold ancient environmental records stretching back to the Pleistocene.",
    content: ""
  }
];

export default function App() {
  const [submitted, setSubmitted] = useState(false);
  const [activeArticleId, setActiveArticleId] = useState<string | null>(null);
  const [sortBy, setSortBy] = useState<SortOption>('latest');

  const selectedArticle = DISPATCHES.find(d => d.id === activeArticleId);

  const sortedDispatches = [...DISPATCHES].sort((a, b) => {
    if (sortBy === 'latest') {
      return new Date(b.date).getTime() - new Date(a.date).getTime();
    }
    if (sortBy === 'oldest') {
      return new Date(a.date).getTime() - new Date(b.date).getTime();
    }
    if (sortBy === 'popular') {
      return b.views - a.views;
    }
    return 0;
  });

  return (
    <div className="min-h-screen bg-[#030914] text-slate-100 font-sans selection:bg-[#CCFF00] selection:text-black">
      
      {/* FIXED NAVBAR */}
      <header className="sticky top-0 z-50 bg-[#030914]/90 backdrop-blur-md border-b border-slate-800/80 px-6 py-4">
        <div className="flex items-center justify-between max-w-6xl mx-auto">
          <div 
            className="flex items-center gap-2 cursor-pointer"
            onClick={() => setActiveArticleId(null)}
          >
            <span className="w-2.5 h-2.5 rounded-full bg-[#CCFF00] animate-pulse"></span>
            <span className="font-bold tracking-widest text-sm text-slate-200">DEEP DISPATCHES</span>
          </div>
          
          <div className="flex items-center gap-4">
            {activeArticleId && (
              <button 
                onClick={() => setActiveArticleId(null)}
                className="text-xs text-[#CCFF00] hover:underline font-mono cursor-pointer"
              >
                ← Back to All Dispatches
              </button>
            )}
            <span className="text-xs text-slate-500 uppercase tracking-widest border border-slate-800 rounded-full px-3 py-1 hidden sm:inline-block">
              Independent Media
            </span>
          </div>
        </div>
      </header>

      {/* VIEW 1: FULL ARTICLE READER */}
      {selectedArticle ? (
        <main className="max-w-3xl mx-auto px-6 py-16 space-y-8">
          <div className="space-y-4">
            <div className="flex items-center gap-3 text-xs font-mono text-[#CCFF00]">
              <span>{selectedArticle.number}</span>
              <span>·</span>
              <span>{selectedArticle.category}</span>
            </div>
            <h1 className="text-3xl md:text-5xl font-extrabold text-white leading-tight">
              {selectedArticle.title}
            </h1>
            <p className="text-lg text-[#CCFF00]/90 font-light italic">
              {selectedArticle.subtitle}
            </p>
            <div className="text-xs text-slate-500 font-mono pt-2 border-b border-slate-800/80 pb-6 flex items-center gap-4">
              <span>Reading Time: {selectedArticle.readTime}</span>
              <span>·</span>
              <span>Status: {selectedArticle.status}</span>
            </div>
          </div>

          <div className="prose prose-invert max-w-none text-slate-300 font-light leading-relaxed space-y-6 pt-4 text-base md:text-lg">
            <p className="first-letter:text-5xl first-letter:font-bold first-letter:text-[#CCFF00] first-letter:mr-3 first-letter:float-left">
              {selectedArticle.summary}
            </p>
            <p>{selectedArticle.excerpt}</p>
            <div className="p-6 bg-[#081225] border-l-2 border-[#CCFF00] rounded-r-lg text-slate-200 font-serif italic my-8">
              "Life on this planet resembles a branching tree – not an arrow."
            </div>
            <p className="text-slate-500 text-sm italic font-mono">
              [Full dossier content is currently being formatted with interactive scrollytelling components...]
            </p>
          </div>
        </main>
      ) : (

      /* VIEW 2: HOME FEED */
      <main className="max-w-4xl mx-auto px-6 py-12 space-y-20">
        
        {/* CINEMATIC FULL HERO CONTAINER WITH VIDEO */}
        <section className="relative rounded-3xl overflow-hidden border border-slate-800/80 min-h-[480px] flex items-center justify-center p-8 md:p-16 shadow-2xl bg-[#081225]">
          
          {/* FULL SCREEN COVER VIDEO LAYER */}
          <div className="absolute inset-0 w-full h-full overflow-hidden pointer-events-none z-0">
            <video 
              autoPlay 
              loop 
              muted 
              playsInline 
              ref={(el) => { if (el) el.muted = true; }}
              className="w-full h-full object-cover opacity-50 scale-105"
            >
              <source src="/bubble.mp4" type="video/mp4" />
            </video>
            {/* Cinematic Gradient Overlays */}
            <div className="absolute inset-0 bg-gradient-to-t from-[#030914] via-[#030914]/40 to-[#030914]/70"></div>
          </div>

          {/* HERO CONTENT LAYER */}
          <div className="relative z-10 text-center space-y-6 max-w-2xl mx-auto">
            <div className="inline-block px-3.5 py-1 bg-slate-900/90 border border-slate-700/80 rounded-full text-xs text-[#CCFF00] font-mono tracking-wider uppercase mb-2 shadow-lg">
              Dispatch #000 · Platform Launch
            </div>
            
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight text-white leading-tight drop-shadow-2xl">
              Far Below The <span className="text-[#CCFF00]">Surface Noise.</span>
            </h1>
            
            <p className="text-base md:text-lg text-slate-200 font-light leading-relaxed drop-shadow-md">
              No social algorithms. Timeless, interactive, and deeply researched ecological investigations delivered directly to your inbox.
            </p>

            {/* BEEHIIV FORM */}
            <div className="pt-2 max-w-md mx-auto">
              {submitted ? (
                <div className="p-4 bg-[#081225]/90 border border-[#CCFF00]/40 rounded-lg text-[#CCFF00] text-sm font-mono backdrop-blur-md">
                  ✓ Subscription request received. Welcome to Deep Dispatches.
                </div>
              ) : (
                <>
                  <form 
                    action="https://app.beehiiv.com/subscribe" 
                    method="POST" 
                    target="beehiiv-target"
                    onSubmit={() => setSubmitted(true)}
                    className="flex flex-col sm:flex-row gap-3"
                  >
                    <input type="hidden" name="publication_id" value="pub_2383c5ca-1813-4b13-b35f-6b498cd01829" />
                    <input
                      type="email"
                      name="email"
                      required
                      placeholder="Enter your email..."
                      className="flex-1 px-4 py-3 bg-[#030914]/90 border border-slate-700 rounded-lg text-white placeholder-slate-500 focus:outline-none focus:border-[#CCFF00] transition-colors"
                    />
                    <button
                      type="submit"
                      className="px-6 py-3 bg-[#CCFF00] hover:bg-[#b8e600] text-black font-semibold rounded-lg transition-colors cursor-pointer whitespace-nowrap shadow-xl"
                    >
                      Subscribe
                    </button>
                  </form>
                  <iframe name="beehiiv-target" className="hidden" title="beehiiv-form-target" />
                </>
              )}
              <p className="text-xs text-slate-400 mt-3 font-medium">No spam. Unsubscribe anytime in one click.</p>
            </div>
          </div>
        </section>

        {/* SCROLLABLE & SORTABLE DISPATCHES STREAM */}
        <section className="space-y-8">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
            <h2 className="text-xs font-mono text-[#CCFF00] tracking-widest uppercase">
              // INVESTIGATION STREAM
            </h2>
            
            <div className="flex items-center gap-2 text-xs font-mono">
              <span className="text-slate-500 mr-1">Sort by:</span>
              <button
                onClick={() => setSortBy('latest')}
                className={`px-3 py-1.5 rounded-lg border transition-all cursor-pointer ${
                  sortBy === 'latest'
                    ? 'bg-[#CCFF00] text-black border-[#CCFF00] font-semibold'
                    : 'bg-[#081225] text-slate-400 border-slate-800 hover:text-white hover:border-slate-700'
                }`}
              >
                Latest
              </button>
              <button
                onClick={() => setSortBy('popular')}
                className={`px-3 py-1.5 rounded-lg border transition-all cursor-pointer ${
                  sortBy === 'popular'
                    ? 'bg-[#CCFF00] text-black border-[#CCFF00] font-semibold'
                    : 'bg-[#081225] text-slate-400 border-slate-800 hover:text-white hover:border-slate-700'
                }`}
              >
                Most Read
              </button>
              <button
                onClick={() => setSortBy('oldest')}
                className={`px-3 py-1.5 rounded-lg border transition-all cursor-pointer ${
                  sortBy === 'oldest'
                    ? 'bg-[#CCFF00] text-black border-[#CCFF00] font-semibold'
                    : 'bg-[#081225] text-slate-400 border-slate-800 hover:text-white hover:border-slate-700'
                }`}
              >
                Oldest
              </button>
            </div>
          </div>

          <div className="space-y-8">
            {sortedDispatches.map((dispatch) => (
              <article 
                key={dispatch.id}
                onClick={() => setActiveArticleId(dispatch.id)}
                className="group bg-[#081225]/50 hover:bg-[#081225] border border-slate-800/80 hover:border-[#CCFF00]/40 rounded-2xl p-8 md:p-10 transition-all duration-300 cursor-pointer relative overflow-hidden shadow-lg"
              >
                <div className="absolute top-0 right-0 w-32 h-32 bg-[#CCFF00]/5 rounded-full blur-2xl group-hover:bg-[#CCFF00]/10 transition-colors pointer-events-none"></div>

                <div className="flex flex-wrap items-center justify-between gap-2 text-xs font-mono text-[#CCFF00] mb-4">
                  <div className="flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-[#CCFF00]"></span>
                    <span>{dispatch.number}</span>
                    <span className="text-slate-600">·</span>
                    <span className="text-slate-400">{dispatch.category}</span>
                  </div>
                  <div className="flex items-center gap-3 text-slate-500">
                    <span>{dispatch.readTime}</span>
                    {sortBy === 'popular' && (
                      <span className="text-[#CCFF00]/80 bg-[#CCFF00]/10 px-2 py-0.5 rounded text-[10px]">
                        {dispatch.views.toLocaleString()} reads
                      </span>
                    )}
                  </div>
                </div>

                <h3 className="text-2xl md:text-3xl font-bold text-white mb-3 group-hover:text-[#CCFF00] transition-colors leading-tight">
                  {dispatch.title}
                </h3>

                <p className="text-slate-300 text-sm md:text-base font-light leading-relaxed mb-6">
                  {dispatch.summary}
                </p>

                <div className="flex items-center justify-between pt-4 border-t border-slate-800/50">
                  <span className="text-xs text-slate-500 font-mono">{dispatch.status}</span>
                  <span className="text-xs font-semibold text-[#CCFF00] group-hover:translate-x-1 transition-transform flex items-center gap-1">
                    Read Investigation →
                  </span>
                </div>
              </article>
            ))}
          </div>
        </section>

        {/* MANIFESTO SECTION */}
        <section className="border-t border-slate-800/80 pt-16 space-y-10">
          <div className="max-w-3xl">
            <h3 className="text-xs font-mono text-[#CCFF00] tracking-widest uppercase mb-4">
              // THE MANIFESTO
            </h3>
            <p className="text-lg md:text-xl text-slate-300 font-light leading-relaxed">
              Welcome to <strong className="text-white font-semibold">Deep Dispatches</strong>, a platform created far below the surface noise. Here, I bridge the gap between Deep Ecology, Marine Mysteries, and the critical worlds of Ecological Finance and Geo-Political Journeys.
            </p>
            <p className="text-base text-slate-400 font-light leading-relaxed mt-4">
              Moving beyond static reporting, I craft visually immersive scrollytelling experiences. Through interactive mapping, dynamic data, and cinematic narratives, I don't just tell these stories—I give you the depth to explore them. Don't miss the horizon.
            </p>
          </div>

          <div className="grid md:grid-cols-3 gap-8 pt-4 border-t border-slate-800/40">
            <div>
              <h4 className="text-sm font-semibold text-[#CCFF00] tracking-wider uppercase mb-2">01. Independent</h4>
              <p className="text-xs text-slate-400 leading-relaxed">Pure journalism uninfluenced by advertisers, algorithms, or clickbait metrics.</p>
            </div>
            <div>
              <h4 className="text-sm font-semibold text-[#CCFF00] tracking-wider uppercase mb-2">02. Immersive</h4>
              <p className="text-xs text-slate-400 leading-relaxed">Interactive scrollytelling, dynamic maps, and data visualizations instead of quick news bites.</p>
            </div>
            <div>
              <h4 className="text-sm font-semibold text-[#CCFF00] tracking-wider uppercase mb-2">03. Timeless</h4>
              <p className="text-xs text-slate-400 leading-relaxed">Deep investigative dossiers built to hold lasting intellectual and ecological value for years.</p>
            </div>
          </div>
        </section>

        {/* THE INVESTIGATOR SECTION WITH PROFILE PHOTO */}
        <section className="border-t border-slate-800/80 pt-16 space-y-6">
          <h3 className="text-xs font-mono